language: c

cache: apt

compiler:
  - gcc
  - clang

before_script:
  - pushd /tmp
#  - wget https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2 -O /tmp/gcc-arm.tar.bz2
#  - tar -xvf /tmp/gcc-arm.tar.bz2
#  - export PATH=/tmp/gcc-arm-none-eabi-5_2-2015q4/bin:$PATH
  - wget https://github.com/greatscottgadgets/libbtbb/archive/master.zip -O /tmp/libbtbb-master.zip
  - unzip libbtbb-master.zip
  - mkdir libbtbb-master/build
  - pushd libbtbb-master/build
  - cmake ..
  - make
  - popd
  - popd
  - export CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array"

script:
  - mkdir host/build
  - pushd host/build
  - cmake -DLIBBTBB_INCLUDE_DIR=/tmp/libbtbb-master/lib/src -DLIBBTBB_LIBRARIES=/tmp/libbtbb-master/build/lib/src/libbtbb.so ..
  - make
#  - popd
#  - pushd firmware
#  - CROSS_COMPILE="/tmp/gcc-arm-none-eabi-5_2-2015q4/bin/arm-none-eabi-" DFU_TOOL="../../host/build/ubertooth-tools/src/ubertooth-dfu" make

addons:
  apt:
    packages:
      - libbluetooth-dev
      - libusb-1.0-0-dev
